<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/Modernizr.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery.countTo.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery.parallax-1.1.3.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery.easing.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery.easypiechart.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery.debouncedresize.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/easyResponsiveTabs.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/lightbox.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery.countdown.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/jquery.mb.YTPlayer.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/masonry.pkgd.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/imagesloaded.pkgd.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/portfolio.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/blog-masonry.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/masonry.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/custom.js"></script>
<script type="text/javascript" src="<?=base_url()?>public/site/js/cart.js"></script>